### PR TITLE
Update cs.json

### PR DESCRIPTION
**Pull request by bhavel**
translated to cs

### CODE REVIEW

**Comment by fnoks** [comment]
Thanks again. You're halfway there :)
https://lang.fnoks.joubel.com/

**Comment by bhavel** [comment]
I have experience with Moodle translations. They will be upgrading to the new system [https://weblate.org/en-gb/](https://weblate.org/en-gb/). Isn't it a challenge for the H5P project?

**Comment by otacke** [comment]
Hi @bhavel 

There already is a community driven site that allows you to contribute translations to H5P using weblate. https://translate-h5p.tk/

**Comment by fnoks** [comment]
@bhavel To answer your question: No, that is not a problem. The translation files for the H5P libraries are not really known by Moodle at all, they are only used in the browser (for the authoring tool and when viewing an H5P)

**Pull request merged**
