### PR TITLE
New Hebrew translation for he.json

### PR DESCRIPTION
**Pull request by nadavkav**

### CODE REVIEW

**Comment by timothyylim** [comment]
Hi @nadavkav , would you be able to resolve the merge conflicts first?

**Comment by nadavkav** [comment]
Something went terribly bad with this PR, I am removing it, and sending a new one.

**Comment by nadavkav** [comment]
Ok. now it looks good.

I do not think github can handle long time hanging PR that have code changes on the master branch.
It seemed you added a new piece of translation (https://github.com/h5p/h5p-true-false/commit/b4081ed737b1e557e7ffc099bc566a2d072dd6a0) that broke a simple diff between master and the patch. weird.

We should have a different kind of a translation system (maybe crowdin, but I think we will have similar issues, as the merge is done by git, at the end), as most users will have trouble managing that kind of changes. I guess.

**Comment by nadavkav** [comment]
I am also trying to use http://jsoneditoronline.org/ for editing a copy of the original EN.JSON into HE, to avoid JSON syntax errors. ( space, comma, brackets, ... )

**Pull request merged**
